---
- hosts: IOS
  gather_facts: no
  connection: network_cli

  tasks:
   - name: OBTAIN LOGIN INFORMATION
     include_vars: secrets.yml

   - name: DEFINE PROVIDER
     set_fact:
       provider:
         host: "{{ ansible_host }}"
         username: "{{ creds['username'] }}"
         password: "{{ creds['password'] }}"
         auth_pass: "{{ creds['auth_pass'] }}"
   
#   - name: run multiple commands on remote nodes
 #     cisco.ios.ios_command:
  #     commands:term mo
   #       - show version
    #      - show interfaces
     #     - term mo

   - name: SET IP ADDRESS
     ios_config:
       provider: "{{ provider }}"
       authorize: yes
       parents: "interface vlan40"
       lines:
         - description SOUTH-CUSTOMER
         - ip address 10.10.20.1 255.255.255.248
         #- ipv6 address 2001:db8:2001::9/64
         - no shutdown
         - do term mo
   
  
 
   - name: show run
     ios_command:
       commands:
           - show run 
          
     #register: config    

   #- name: save output to local directory
    # copy:
     #      content: "{{ config.stdout | replace('\\n', '\n') }}"           dest: "show-output/{{ inventory_hostname }}.ios"
 #...    